name: ACCNeoX
options:
  bundleIdPrefix: net.acloudradius
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  MARKETING_VERSION: 1.0
  CURRENT_PROJECT_VERSION: 1

targets:
  ACCNeoX:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: ACCNeoX
        excludes:
          - "*.md"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: net.acloudradius.neox
      DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "$(CODE_SIGN_IDENTITY)"
      PROVISIONING_PROFILE_SPECIFIER: "$(PROVISIONING_PROFILE_NAME)"
      INFOPLIST_FILE: ACCNeoX/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1,2"

schemes:
  ACCNeoX:
    build:
      targets:
        ACCNeoX: all
    run:
      config: Debug
    archive:
      config: Release